#pragma config(Motor,  port5,           bottom_right,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           bottom_left,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           top_right,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           top_left,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1 == 1)
  {
  	//motor[front_left]=100;
    //Right side of the robot is controlled by the right joystick, Y-axis
    motor[bottom_right] = vexRT[Ch2];
    motor[top_right]  = vexRT[Ch1];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[bottom_left] = vexRT[Ch3];
    motor[top_left]  = vexRT[Ch4];
 	}


}
