#pragma config(Motor,  port5,          LeftFrontMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LeftBackMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,          RightBackMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,          RightFrontMotor, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(1==1)
	{
		motor[LeftFrontMotor]= vexRT[Ch2] + vexRT[Ch1] + vexRT[Ch4];
		motor[LeftBackMotor]= vexRT[Ch2] - vexRT[Ch1] + vexRT[Ch4];
		motor[RightBackMotor]= (-vexRT[Ch2]) + vexRT[Ch1] + vexRT[Ch4];
		motor[RightFrontMotor]= (-vexRT[Ch2]) - vexRT[Ch1] + vexRT[Ch4];
	}

}
